version: '3'
services:
  external:
    container_name: external
    image: navigator-svelte
    build:
      context: .
      dockerfile: Dockerfile
    user: 'node'
    environment:
      # Sets the timezone of the containers OS
      - TZ=America/Buenos_Aires
    # Points to a file with the sensitive environment variables
    env_file:
      - ./env/.env.${NODE_ENV}
    restart: unless-stopped
    ports:
      - '3000:5050'
