export const icons = {
	'fa fa-bar-chart': `/img/icons/bar.png`,
	'fa fa-area-chart': `/img/icons/area.png`,
	'fa fa-table': `/img/icons/table.png`,
	'fa fa-circle-o-notch': `/img/icons/pie-2.png`,
	'fa fa-tachometer': `/img/icons/speedometer.png`,
	'fa fa-id-card-o': `/img/icons/id.png`,
	'tabler:cards': `/img/icons/id.png`,
	'tabler:file-settings': `/img/icons/pin.png`,
	'tabler:file-type-pdf': `/img/icons/pdf.png`,
	'fa fa-map': `/img/icons/map.png`,
	'fa fa-clock-o': `/img/icons/clock.png`,
	'far fa-rss': `/img/icons/rss.png`,
	'fa fa-desktop': `/img/icons/pc.png`,
	'material-symbols:iframe': `/img/icons/pc.png`,
	'fa fa-file-image-o': `/img/icons/photo.png`,
	'fa fa-film': `/img/icons/cinema.png`,
	'fa fa-youtube': `/img/icons/youtube.png`,
	'tabler:brand-youtube': `/img/icons/youtube.png`,
	'tabler:brand-spotify': `/img/icons/spotify.svg`,
	'tabler:brand-vimeo': `/img/icons/vimeo.svg`,
	'tabler:brand-x': `/img/icons/twitterX.svg`,
	'tabler:timeline': `/img/icons/timeline.png`,
	'tabler:plug-connected': `/img/icons/enlace.png`,
	'tabler:list-check': `/img/icons/enlace.png`,
	'tabler:list-tree': `/img/icons/documents.png`,
	'tabler:carousel-horizontal': `/img/icons/gallery.png`,
	'tabler:wash-dry-shade': `/img/icons/content.png`,
	undefined: `/img/icons/pc.png`,
	loading: `/img/icons/loading.svg`,
	'fa fa-flickr': `/img/icons/flickr.svg`
}
