# NAV Api V2

###
# group: Dashboards
# @name Meta Info dashboards
GET https://api.dev.navigator.mobileinsight.com/api/v2/dashboards:meta
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1NDU0ODUsImlhdCI6MTY5NDE4NTQ4NSwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjM1LCJ1c2VybmFtZSI6ImpsYXJhQHRyb2NnbG9iYWwuY29tIiwidXNlcl9pZCI6MzUsImlkIjoiamxhcmFAdHJvY2dsb2JhbC5jb20ifQ.foapyL2b1VN6wTv0NDtbo-WLGOB1sikkxZIN7ycVtkU

###
# group: Dashboards
# @name Metadata
HEAD https://api.dev.navigator.mobileinsight.com/api/v2/dashboards:meta
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1NDU0ODUsImlhdCI6MTY5NDE4NTQ4NSwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjM1LCJ1c2VybmFtZSI6ImpsYXJhQHRyb2NnbG9iYWwuY29tIiwidXNlcl9pZCI6MzUsImlkIjoiamxhcmFAdHJvY2dsb2JhbC5jb20ifQ.foapyL2b1VN6wTv0NDtbo-WLGOB1sikkxZIN7ycVtkU

###
# group: Dashboards
# @name Sample Dashboard Data
GET https://api.dev.navigator.mobileinsight.com/api/v2/dashboards:sample
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1NDU0ODUsImlhdCI6MTY5NDE4NTQ4NSwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjM1LCJ1c2VybmFtZSI6ImpsYXJhQHRyb2NnbG9iYWwuY29tIiwidXNlcl9pZCI6MzUsImlkIjoiamxhcmFAdHJvY2dsb2JhbC5jb20ifQ.foapyL2b1VN6wTv0NDtbo-WLGOB1sikkxZIN7ycVtkU

###
# group: Dashboards
# @name Get one Dashboard
GET https://api.dev.navigator.mobileinsight.com/api/v2/dashboards?
    program_id=19&
    module_id=114&
    explorer=false
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTY5NzI0MjQsImlhdCI6MTY5NjYxMjQyNCwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjE1Nzc5LCJ1c2VybmFtZSI6ImptZW5kb3phMUB0cm9jZ2xvYmFsLmNvbSIsInVzZXJfaWQiOjE1Nzc5LCJpZCI6ImptZW5kb3phMUB0cm9jZ2xvYmFsLmNvbSJ9.gRS3837D5E8dYqeBqr_l22vhvM2bIN9kROK_PyYQOMw

###
# group: Dashboards
# @name Get one Dashboard DEV
GET https://api.dev.navigator.mobileinsight.com/api/v2/dashboards?
    program_id=19&
    module_id=114&
    explorer=false
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTY3MDQ0MTgsImlhdCI6MTY5NjM0NDQxOCwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjE1Nzc5LCJ1c2VybmFtZSI6ImptZW5kb3phMUB0cm9jZ2xvYmFsLmNvbSIsInVzZXJfaWQiOjE1Nzc5LCJpZCI6ImptZW5kb3phMUB0cm9jZ2xvYmFsLmNvbSJ9.1gua2Lpngbptjs8YhUgoCf7wmc_FQdEIwy6Z8sFiBDQ

###
# group: Dashboards
# @name Get all Dashboards
GET https://api.dev.navigator.mobileinsight.com/api/v2/dashboards?
    duid=325643c2-dcc6-410e-85a7-af10d98743c2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTY5NzI0MjQsImlhdCI6MTY5NjYxMjQyNCwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjE1Nzc5LCJ1c2VybmFtZSI6ImptZW5kb3phMUB0cm9jZ2xvYmFsLmNvbSIsInVzZXJfaWQiOjE1Nzc5LCJpZCI6ImptZW5kb3phMUB0cm9jZ2xvYmFsLmNvbSJ9.gRS3837D5E8dYqeBqr_l22vhvM2bIN9kROK_PyYQOMw

###
# group: Dashboards
# @name Get Dashboards from Module
GET https://api.dev.navigator.mobileinsight.com/api/v2/dashboards?
    program_id=19&
    module_id=122&
    explorer=false
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1NDU0ODUsImlhdCI6MTY5NDE4NTQ4NSwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjM1LCJ1c2VybmFtZSI6ImpsYXJhQHRyb2NnbG9iYWwuY29tIiwidXNlcl9pZCI6MzUsImlkIjoiamxhcmFAdHJvY2dsb2JhbC5jb20ifQ.foapyL2b1VN6wTv0NDtbo-WLGOB1sikkxZIN7ycVtkU

###
# group: Dashboards
# @name Dashboard clone
POST https://api.dev.navigator.mobileinsight.com/api/v2/dashboard/clone
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1NDU0ODUsImlhdCI6MTY5NDE4NTQ4NSwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjM1LCJ1c2VybmFtZSI6ImpsYXJhQHRyb2NnbG9iYWwuY29tIiwidXNlcl9pZCI6MzUsImlkIjoiamxhcmFAdHJvY2dsb2JhbC5jb20ifQ.foapyL2b1VN6wTv0NDtbo-WLGOB1sikkxZIN7ycVtkU
Content-Type: application/json

{
  "duid": "4c30b3e9-51b0-489e-b832-36147d4cb4bf",
  "module_id": 5
}

###
# group: Dashboards
# @name Insert Dashboard
PUT https://api.dev.navigator.mobileinsight.com/api/v2/dashboards
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1NDU0ODUsImlhdCI6MTY5NDE4NTQ4NSwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjM1LCJ1c2VybmFtZSI6ImpsYXJhQHRyb2NnbG9iYWwuY29tIiwidXNlcl9pZCI6MzUsImlkIjoiamxhcmFAdHJvY2dsb2JhbC5jb20ifQ.foapyL2b1VN6wTv0NDtbo-WLGOB1sikkxZIN7ycVtkU
Content-Type: application/json

{
  "dashboard_name": "Este es un nuevo dashboard"
}

###
# group: Dashboards
# @name Update dashboard
POST https://api.dev.navigator.mobileinsight.com/api/v2/dashboards/93e7339a-d11d-4683-abfd-c3fc161f5c6c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1NDU0ODUsImlhdCI6MTY5NDE4NTQ4NSwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjM1LCJ1c2VybmFtZSI6ImpsYXJhQHRyb2NnbG9iYWwuY29tIiwidXNlcl9pZCI6MzUsImlkIjoiamxhcmFAdHJvY2dsb2JhbC5jb20ifQ.foapyL2b1VN6wTv0NDtbo-WLGOB1sikkxZIN7ycVtkU
Content-Type: application/json

{
  "module_id": 6
}

###
# group: Dashboards
# @name Dashboard impersonation
PATCH https://api.dev.navigator.mobileinsight.com/api/v2/dashboards
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1NDU0ODUsImlhdCI6MTY5NDE4NTQ4NSwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjM1LCJ1c2VybmFtZSI6ImpsYXJhQHRyb2NnbG9iYWwuY29tIiwidXNlcl9pZCI6MzUsImlkIjoiamxhcmFAdHJvY2dsb2JhbC5jb20ifQ.foapyL2b1VN6wTv0NDtbo-WLGOB1sikkxZIN7ycVtkU
Content-Type: application/json

{
  "dashboard_id": 106,
  "impersonation": false
}

###
# group: Dashboards
# @name Delete dashboard and children widgets
DELETE https://api.dev.navigator.mobileinsight.com/api/v2/dashboards/63b16d07-6e52-4c36-9bed-f85ff5e32822
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1NDU0ODUsImlhdCI6MTY5NDE4NTQ4NSwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjM1LCJ1c2VybmFtZSI6ImpsYXJhQHRyb2NnbG9iYWwuY29tIiwidXNlcl9pZCI6MzUsImlkIjoiamxhcmFAdHJvY2dsb2JhbC5jb20ifQ.foapyL2b1VN6wTv0NDtbo-WLGOB1sikkxZIN7ycVtkU
Content-Type: application/json

{
  "duid": "63b16d07-6e52-4c36-9bed-f85ff5e32822"
}

###
# group: Save Filtering
# @name Filtering by Program
GET https://api.dev.navigator.mobileinsight.com/api/v2/save-filtering?
    program_slug=walmart
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1NDU0ODUsImlhdCI6MTY5NDE4NTQ4NSwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjM1LCJ1c2VybmFtZSI6ImpsYXJhQHRyb2NnbG9iYWwuY29tIiwidXNlcl9pZCI6MzUsImlkIjoiamxhcmFAdHJvY2dsb2JhbC5jb20ifQ.foapyL2b1VN6wTv0NDtbo-WLGOB1sikkxZIN7ycVtkU

###
# group: Save Filtering
# @name Get all Filters by Current User
GET https://api.dev.navigator.mobileinsight.com/api/v2/save-filtering
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1NDU0ODUsImlhdCI6MTY5NDE4NTQ4NSwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjM1LCJ1c2VybmFtZSI6ImpsYXJhQHRyb2NnbG9iYWwuY29tIiwidXNlcl9pZCI6MzUsImlkIjoiamxhcmFAdHJvY2dsb2JhbC5jb20ifQ.foapyL2b1VN6wTv0NDtbo-WLGOB1sikkxZIN7ycVtkU

###
# group: Save Filtering
# @name Using Filter in Save Filter
GET https://api.dev.navigator.mobileinsight.com/api/v2/save-filtering?
    filter_name=Iowa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1NDU0ODUsImlhdCI6MTY5NDE4NTQ4NSwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjM1LCJ1c2VybmFtZSI6ImpsYXJhQHRyb2NnbG9iYWwuY29tIiwidXNlcl9pZCI6MzUsImlkIjoiamxhcmFAdHJvY2dsb2JhbC5jb20ifQ.foapyL2b1VN6wTv0NDtbo-WLGOB1sikkxZIN7ycVtkU

###
# group: Save Filtering
# @name Create a filtering
PUT https://api.dev.navigator.mobileinsight.com/api/v2/save-filtering
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1NDU0ODUsImlhdCI6MTY5NDE4NTQ4NSwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjM1LCJ1c2VybmFtZSI6ImpsYXJhQHRyb2NnbG9iYWwuY29tIiwidXNlcl9pZCI6MzUsImlkIjoiamxhcmFAdHJvY2dsb2JhbC5jb20ifQ.foapyL2b1VN6wTv0NDtbo-WLGOB1sikkxZIN7ycVtkU
Content-Type: application/json

{
  "conditions": {}
}

###
# group: Save Filtering
# @name Update a filtering
POST https://api.dev.navigator.mobileinsight.com/api/v2/save-filtering/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1NDU0ODUsImlhdCI6MTY5NDE4NTQ4NSwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjM1LCJ1c2VybmFtZSI6ImpsYXJhQHRyb2NnbG9iYWwuY29tIiwidXNlcl9pZCI6MzUsImlkIjoiamxhcmFAdHJvY2dsb2JhbC5jb20ifQ.foapyL2b1VN6wTv0NDtbo-WLGOB1sikkxZIN7ycVtkU
Content-Type: application/json

{
  "filter_id": 3,
  "filter_name": "filtering actualizado 1",
  "conditions": {}
}

###
# group: Save Filtering
# @name Delete a filtering
DELETE https://api.dev.navigator.mobileinsight.com/api/v2/save-filtering
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1NDU0ODUsImlhdCI6MTY5NDE4NTQ4NSwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjM1LCJ1c2VybmFtZSI6ImpsYXJhQHRyb2NnbG9iYWwuY29tIiwidXNlcl9pZCI6MzUsImlkIjoiamxhcmFAdHJvY2dsb2JhbC5jb20ifQ.foapyL2b1VN6wTv0NDtbo-WLGOB1sikkxZIN7ycVtkU
Content-Type: application/json

{
  "filter_id": 27
}

###
# group: Save Filtering
# @name Delete a filtering by Key
DELETE https://api.dev.navigator.mobileinsight.com/api/v2/save-filtering/33
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1NDU0ODUsImlhdCI6MTY5NDE4NTQ4NSwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjM1LCJ1c2VybmFtZSI6ImpsYXJhQHRyb2NnbG9iYWwuY29tIiwidXNlcl9pZCI6MzUsImlkIjoiamxhcmFAdHJvY2dsb2JhbC5jb20ifQ.foapyL2b1VN6wTv0NDtbo-WLGOB1sikkxZIN7ycVtkU

###
# group: Widgets / Template
# @name Get all Widget Templates
GET https://api.dev.navigator.mobileinsight.com/api/v2/widgets-template
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTY5NzI0MjQsImlhdCI6MTY5NjYxMjQyNCwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjE1Nzc5LCJ1c2VybmFtZSI6ImptZW5kb3phMUB0cm9jZ2xvYmFsLmNvbSIsInVzZXJfaWQiOjE1Nzc5LCJpZCI6ImptZW5kb3phMUB0cm9jZ2xvYmFsLmNvbSJ9.gRS3837D5E8dYqeBqr_l22vhvM2bIN9kROK_PyYQOMw

###
# group: Widgets / Template
# @name Widget Templates by Program
GET https://api.dev.navigator.mobileinsight.com/api/v2/widgets-template?program_id=3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTY5NzI0MjQsImlhdCI6MTY5NjYxMjQyNCwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjE1Nzc5LCJ1c2VybmFtZSI6ImptZW5kb3phMUB0cm9jZ2xvYmFsLmNvbSIsInVzZXJfaWQiOjE1Nzc5LCJpZCI6ImptZW5kb3phMUB0cm9jZ2xvYmFsLmNvbSJ9.gRS3837D5E8dYqeBqr_l22vhvM2bIN9kROK_PyYQOMw

###
# group: Widgets / Template
# @name Get One Widget Template
GET https://api.dev.navigator.mobileinsight.com/api/v2/widgets-template/b13b619a-847e-4734-a3d2-fa198f0531b7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1NDU0ODUsImlhdCI6MTY5NDE4NTQ4NSwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjM1LCJ1c2VybmFtZSI6ImpsYXJhQHRyb2NnbG9iYWwuY29tIiwidXNlcl9pZCI6MzUsImlkIjoiamxhcmFAdHJvY2dsb2JhbC5jb20ifQ.foapyL2b1VN6wTv0NDtbo-WLGOB1sikkxZIN7ycVtkU

###
# group: Widgets / Template
# @name Insert Widget Template
PUT https://api.dev.navigator.mobileinsight.com/api/v2/widgets-template
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1NDU0ODUsImlhdCI6MTY5NDE4NTQ4NSwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjM1LCJ1c2VybmFtZSI6ImpsYXJhQHRyb2NnbG9iYWwuY29tIiwidXNlcl9pZCI6MzUsImlkIjoiamxhcmFAdHJvY2dsb2JhbC5jb20ifQ.foapyL2b1VN6wTv0NDtbo-WLGOB1sikkxZIN7ycVtkU
Content-Type: application/json

{
  "widget_type_id": "api-card",
  "widget_name": "Nuevo widget Template",
  "widget_slug": "iframe",
  "widgetcat_id": 3
}

###
# group: Widgets / Template
# @name Patch a Widget Template
PATCH https://api.dev.navigator.mobileinsight.com/api/v2/widgets-template/702269d6-d3d2-4f75-9fc3-d994acad39f3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTc3ODYxNjQsImlhdCI6MTY5NzQyNjE2NCwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjE1Nzc5LCJ1c2VybmFtZSI6ImptZW5kb3phMUB0cm9jZ2xvYmFsLmNvbSIsInVzZXJfaWQiOjE1Nzc5LCJpZCI6ImptZW5kb3phMUB0cm9jZ2xvYmFsLmNvbSJ9.KPNEDn0za2tO1IQni4j5s-pR7EZqFEjRz4xmaGyFG6c
Content-Type: application/json

{
  "widget_name": "New Browser Widget"
}

###
# group: Widgets / Template
# @name Edit a Widget Template
POST https://api.dev.navigator.mobileinsight.com/api/v2/widgets-template
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1NDU0ODUsImlhdCI6MTY5NDE4NTQ4NSwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjM1LCJ1c2VybmFtZSI6ImpsYXJhQHRyb2NnbG9iYWwuY29tIiwidXNlcl9pZCI6MzUsImlkIjoiamxhcmFAdHJvY2dsb2JhbC5jb20ifQ.foapyL2b1VN6wTv0NDtbo-WLGOB1sikkxZIN7ycVtkU
Content-Type: application/json

{
  "widget_id": 7,
  "uid": "b13b619a-847e-4734-a3d2-fa198f0531b7",
  "widget_name": "Browser Widget",
  "title": "Iframe Widget",
  "description": "Container for Iframe URL",
  "url": "https://time.is/Miami",
  "active": true,
  "params": {
    "url": "https://time.is/Miami"
  },
  "embed": null,
  "attributes": {
    "icon": "fa fa-desktop",
    "color": "#ffffff",
    "fg_color": "#333"
  },
  "conditions": null,
  "cond_definition": {},
  "where_definition": [
    "territory_id",
    "region_name",
    "district_id",
    "market_id",
    "store_id"
  ],
  "format_definition": null,
  "master_filtering": true,
  "query_slug": null,
  "widget_slug": "iframe",
  "program_id": 3,
  "widget_type_id": "iframe",
  "widgetcat_id": 3,
  "allow_filtering": true,
  "filtering_show": null,
  "inserted_at": "2022-09-22T17:44:15.778812Z",
  "inserted_by": null,
  "updated_at": "2023-05-16T02:39:46.993656Z",
  "updated_by": null
}

###
# group: Widgets
# @name Get all Widgets
GET https://api.dev.navigator.mobileinsight.com/api/v2/widgets?
    dashboard_id=25
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTY5NzI0MjQsImlhdCI6MTY5NjYxMjQyNCwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjE1Nzc5LCJ1c2VybmFtZSI6ImptZW5kb3phMUB0cm9jZ2xvYmFsLmNvbSIsInVzZXJfaWQiOjE1Nzc5LCJpZCI6ImptZW5kb3phMUB0cm9jZ2xvYmFsLmNvbSJ9.gRS3837D5E8dYqeBqr_l22vhvM2bIN9kROK_PyYQOMw
Content-Type: application/x-www-form-urlencoded

###
# group: Widgets
# @name Get all Widgets Copy
GET https://api.dev.navigator.mobileinsight.com/api/v2/widgets?
    dashboard_id=2977
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1NDU0ODUsImlhdCI6MTY5NDE4NTQ4NSwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjM1LCJ1c2VybmFtZSI6ImpsYXJhQHRyb2NnbG9iYWwuY29tIiwidXNlcl9pZCI6MzUsImlkIjoiamxhcmFAdHJvY2dsb2JhbC5jb20ifQ.foapyL2b1VN6wTv0NDtbo-WLGOB1sikkxZIN7ycVtkU
Content-Type: application/x-www-form-urlencoded

###
# group: Widgets
# @name Update Widget
POST http://nav-api.dev.local:5001/api/v2/widgets/ba935f5a-1517-11ed-a133-0a62d3955ea3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1NDU0ODUsImlhdCI6MTY5NDE4NTQ4NSwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjM1LCJ1c2VybmFtZSI6ImpsYXJhQHRyb2NnbG9iYWwuY29tIiwidXNlcl9pZCI6MzUsImlkIjoiamxhcmFAdHJvY2dsb2JhbC5jb20ifQ.foapyL2b1VN6wTv0NDtbo-WLGOB1sikkxZIN7ycVtkU
Content-Type: application/json

{
  "description": "Description widget v8"
}

###
# group: Widgets
# @name Insert Widget
PUT https://api.dev.navigator.mobileinsight.com/api/v2/widgets/ba935f5a-1517-11ed-a133-0a62d395
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTc4Mjc2MTMsImlhdCI6MTY5NzQ2NzYxMywiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjE1Nzc5LCJ1c2VybmFtZSI6ImptZW5kb3phMUB0cm9jZ2xvYmFsLmNvbSIsInVzZXJfaWQiOjE1Nzc5LCJpZCI6ImptZW5kb3phMUB0cm9jZ2xvYmFsLmNvbSJ9.PXZ2blxrSHfFtGKy-NRhPZVprIuBq8Ps7xrZqm3HgCg
Content-Type: application/json

{
  "program_id": 1,
  "dashboard_id": 557,
  "title": "Nuevo widget v7",
  "widget_id": 278
}
###
# group: Widgets
# @name Delete Widget
DELETE https://api.dev.navigator.mobileinsight.com/api/v2/widgets/f88ae5b7-2b03-44b0-b8db-bf85b63be0f1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjcwMDU4NDQsImlhdCI6MTY2NjY0NTg0NCwiaXNzIjoidXJuOk5hdmlnYXRvciIsInVzZXIiOjEzMTQ0LCJ1c2VybmFtZSI6IkdjYW5lbG9uQG1vYmlsZWluc2lnaHQuY29tIiwidXNlcl9pZCI6MTMxNDQsImlkIjoiR2NhbmVsb25AbW9iaWxlaW5zaWdodC5jb20ifQ.uHnsuYfDnOLPWWzdUjfs5kZqIBgFZcEfXLQQEVk2S60

###
# group: Widgets
# @name Create Widget from Widget Template
PATCH http://nav-api.dev.local:5001/api/v2/widgets?
    uid=534f449d-54f3-4b99-ac8a-25fb1a8c0916
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjUxNjc0NTIsImlhdCI6MTY2NDgwNzQ1MiwiaXNzIjoidXJuOk5hdmlnYXRvciIsInVzZXIiOjEzMTQ0LCJ1c2VybmFtZSI6IkdjYW5lbG9uQG1vYmlsZWluc2lnaHQuY29tIiwidXNlcl9pZCI6MTMxNDQsImlkIjoiR2NhbmVsb25AbW9iaWxlaW5zaWdodC5jb20ifQ.gSPPiW8kEsbC9vE4HB68EvnPXGkdnGHOQc51Huoyk9M
Content-Type: application/json

{
  "dashboard_id": 106,
  "program_id": 4
}

###
# group: Programs
# @name Update program with clients and groups
POST http://nav-api.dev.local:5001/api/v2/programs/new-program-h
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1NDU0ODUsImlhdCI6MTY5NDE4NTQ4NSwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjM1LCJ1c2VybmFtZSI6ImpsYXJhQHRyb2NnbG9iYWwuY29tIiwidXNlcl9pZCI6MzUsImlkIjoiamxhcmFAdHJvY2dsb2JhbC5jb20ifQ.foapyL2b1VN6wTv0NDtbo-WLGOB1sikkxZIN7ycVtkU
Content-Type: application/json

{
  "program_name": "Test update 22"
}

###
# group: Programs
# @name Create new program with clients and groups
PUT http://nav-api.dev.local:5001/api/v2/programs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1NDU0ODUsImlhdCI6MTY5NDE4NTQ4NSwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjM1LCJ1c2VybmFtZSI6ImpsYXJhQHRyb2NnbG9iYWwuY29tIiwidXNlcl9pZCI6MzUsImlkIjoiamxhcmFAdHJvY2dsb2JhbC5jb20ifQ.foapyL2b1VN6wTv0NDtbo-WLGOB1sikkxZIN7ycVtkU
Content-Type: application/json

{
  "program_name": "Test New Program",
  "program_slug": "new-program-h",
  "image_url": "/test/image/hola.png",
  "clientsId": [
    1
  ],
  "clientsSlug": [
    "navigator"
  ],
  "groups": [
    1
  ],
  "ordering": 1
}

###
# group: Programs
# @name Get all Programs with user
GET https://api.dev.navigator.mobileinsight.com/api/v1/programs_user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1NDU0ODUsImlhdCI6MTY5NDE4NTQ4NSwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjM1LCJ1c2VybmFtZSI6ImpsYXJhQHRyb2NnbG9iYWwuY29tIiwidXNlcl9pZCI6MzUsImlkIjoiamxhcmFAdHJvY2dsb2JhbC5jb20ifQ.foapyL2b1VN6wTv0NDtbo-WLGOB1sikkxZIN7ycVtkU

###
# group: Modules
# @name Get all modules django
POST https://api.dev.navigator.mobileinsight.com/api/v2/modules
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1NDU0ODUsImlhdCI6MTY5NDE4NTQ4NSwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjM1LCJ1c2VybmFtZSI6ImpsYXJhQHRyb2NnbG9iYWwuY29tIiwidXNlcl9pZCI6MzUsImlkIjoiamxhcmFAdHJvY2dsb2JhbC5jb20ifQ.foapyL2b1VN6wTv0NDtbo-WLGOB1sikkxZIN7ycVtkU
Content-Type: application/json

{
  "client_id": 1,
  "client_slug": "navigator",
  "program_slug": "partner_portal",
  "module": {
    "module_name": "partner_portal_test",
    "module_slug": "partner_portal_test",
    "classname": "Partner_portalTest",
    "active": true,
    "program_id": 16,
    "description": "Test",
    "attributes": {
      "color": "#ffffff",
      "icon": "fa fa-desktop",
      "quick": false,
      "width": "720",
      "height": "480"
    }
  },
  "dashboard_id": 2904
}

###
# group: Modules
# @name Get all modules
GET https://api.dev.navigator.mobileinsight.com/api/v2/modules
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1NDU0ODUsImlhdCI6MTY5NDE4NTQ4NSwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjM1LCJ1c2VybmFtZSI6ImpsYXJhQHRyb2NnbG9iYWwuY29tIiwidXNlcl9pZCI6MzUsImlkIjoiamxhcmFAdHJvY2dsb2JhbC5jb20ifQ.foapyL2b1VN6wTv0NDtbo-WLGOB1sikkxZIN7ycVtkU
Origin: https://claro-vtr.provectis.mobileinsight.com

###
# group: Modules
# @name All Module Clients
GET https://api.dev.navigator.mobileinsight.com/api/v1/module_clients
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1NDU0ODUsImlhdCI6MTY5NDE4NTQ4NSwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjM1LCJ1c2VybmFtZSI6ImpsYXJhQHRyb2NnbG9iYWwuY29tIiwidXNlcl9pZCI6MzUsImlkIjoiamxhcmFAdHJvY2dsb2JhbC5jb20ifQ.foapyL2b1VN6wTv0NDtbo-WLGOB1sikkxZIN7ycVtkU

###
# group: Groups
# @name Meta Info
GET https://api.dev.navigator.mobileinsight.com/api/v2/groups:meta
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1NDU0ODUsImlhdCI6MTY5NDE4NTQ4NSwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjM1LCJ1c2VybmFtZSI6ImpsYXJhQHRyb2NnbG9iYWwuY29tIiwidXNlcl9pZCI6MzUsImlkIjoiamxhcmFAdHJvY2dsb2JhbC5jb20ifQ.foapyL2b1VN6wTv0NDtbo-WLGOB1sikkxZIN7ycVtkU

###
# group: Groups
# @name Metadata
HEAD https://api.dev.navigator.mobileinsight.com/api/v2/groups
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1NDU0ODUsImlhdCI6MTY5NDE4NTQ4NSwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjM1LCJ1c2VybmFtZSI6ImpsYXJhQHRyb2NnbG9iYWwuY29tIiwidXNlcl9pZCI6MzUsImlkIjoiamxhcmFAdHJvY2dsb2JhbC5jb20ifQ.foapyL2b1VN6wTv0NDtbo-WLGOB1sikkxZIN7ycVtkU

###
# group: Groups
# @name Sample Group Data
GET https://api.dev.navigator.mobileinsight.com/api/v2/groups:sample
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1NDU0ODUsImlhdCI6MTY5NDE4NTQ4NSwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjM1LCJ1c2VybmFtZSI6ImpsYXJhQHRyb2NnbG9iYWwuY29tIiwidXNlcl9pZCI6MzUsImlkIjoiamxhcmFAdHJvY2dsb2JhbC5jb20ifQ.foapyL2b1VN6wTv0NDtbo-WLGOB1sikkxZIN7ycVtkU

###
# group: Groups
# @name Get All Groups
GET https://api.dev.navigator.mobileinsight.com/api/v2/groups
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1NDU0ODUsImlhdCI6MTY5NDE4NTQ4NSwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjM1LCJ1c2VybmFtZSI6ImpsYXJhQHRyb2NnbG9iYWwuY29tIiwidXNlcl9pZCI6MzUsImlkIjoiamxhcmFAdHJvY2dsb2JhbC5jb20ifQ.foapyL2b1VN6wTv0NDtbo-WLGOB1sikkxZIN7ycVtkU

###
# group: Groups
# @name Get One Group
GET https://api.dev.navigator.mobileinsight.com/api/v2/groups/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1NDU0ODUsImlhdCI6MTY5NDE4NTQ4NSwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjM1LCJ1c2VybmFtZSI6ImpsYXJhQHRyb2NnbG9iYWwuY29tIiwidXNlcl9pZCI6MzUsImlkIjoiamxhcmFAdHJvY2dsb2JhbC5jb20ifQ.foapyL2b1VN6wTv0NDtbo-WLGOB1sikkxZIN7ycVtkU

###
# group: Groups
# @name Get Multiple Groups
GET https://api.dev.navigator.mobileinsight.com/api/v2/groups/1/2/3/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1NDU0ODUsImlhdCI6MTY5NDE4NTQ4NSwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjM1LCJ1c2VybmFtZSI6ImpsYXJhQHRyb2NnbG9iYWwuY29tIiwidXNlcl9pZCI6MzUsImlkIjoiamxhcmFAdHJvY2dsb2JhbC5jb20ifQ.foapyL2b1VN6wTv0NDtbo-WLGOB1sikkxZIN7ycVtkU

###
# group: Groups
# @name Get Groups by Filter
GET https://api.dev.navigator.mobileinsight.com/api/v2/groups/?
    group_name=superuser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1NDU0ODUsImlhdCI6MTY5NDE4NTQ4NSwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjM1LCJ1c2VybmFtZSI6ImpsYXJhQHRyb2NnbG9iYWwuY29tIiwidXNlcl9pZCI6MzUsImlkIjoiamxhcmFAdHJvY2dsb2JhbC5jb20ifQ.foapyL2b1VN6wTv0NDtbo-WLGOB1sikkxZIN7ycVtkU

###
# group: Groups
# @name Patch a Group
PATCH https://api.dev.navigator.mobileinsight.com/api/v2/groups/13
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1NDU0ODUsImlhdCI6MTY5NDE4NTQ4NSwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjM1LCJ1c2VybmFtZSI6ImpsYXJhQHRyb2NnbG9iYWwuY29tIiwidXNlcl9pZCI6MzUsImlkIjoiamxhcmFAdHJvY2dsb2JhbC5jb20ifQ.foapyL2b1VN6wTv0NDtbo-WLGOB1sikkxZIN7ycVtkU
Content-Type: application/json

{
  "is_active": false
}

###
# group: Groups
# @name New Group
PUT https://api.dev.navigator.mobileinsight.com/api/v2/groups
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1NDU0ODUsImlhdCI6MTY5NDE4NTQ4NSwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjM1LCJ1c2VybmFtZSI6ImpsYXJhQHRyb2NnbG9iYWwuY29tIiwidXNlcl9pZCI6MzUsImlkIjoiamxhcmFAdHJvY2dsb2JhbC5jb20ifQ.foapyL2b1VN6wTv0NDtbo-WLGOB1sikkxZIN7ycVtkU
Content-Type: application/json

{
  "group_name": "My Sample Group",
  "client_id": null,
  "is_active": true
}

###
# group: Groups
# @name Error on New Group (failed required)
PUT https://api.dev.navigator.mobileinsight.com/api/v2/groups
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1NDU0ODUsImlhdCI6MTY5NDE4NTQ4NSwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjM1LCJ1c2VybmFtZSI6ImpsYXJhQHRyb2NnbG9iYWwuY29tIiwidXNlcl9pZCI6MzUsImlkIjoiamxhcmFAdHJvY2dsb2JhbC5jb20ifQ.foapyL2b1VN6wTv0NDtbo-WLGOB1sikkxZIN7ycVtkU
Content-Type: application/json

{
  "client_id": null,
  "is_active": true
}

###
# group: Groups
# @name Edit Group
POST https://api.dev.navigator.mobileinsight.com/api/v2/groups/106
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1NDU0ODUsImlhdCI6MTY5NDE4NTQ4NSwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjM1LCJ1c2VybmFtZSI6ImpsYXJhQHRyb2NnbG9iYWwuY29tIiwidXNlcl9pZCI6MzUsImlkIjoiamxhcmFAdHJvY2dsb2JhbC5jb20ifQ.foapyL2b1VN6wTv0NDtbo-WLGOB1sikkxZIN7ycVtkU
Content-Type: application/json

{
  "group_id": 106,
  "group_name": "My Sample Group",
  "client_id": 1,
  "is_active": false,
  "created_at": "2023-05-15T21:29:01.907037Z",
  "updated_at": "2023-05-15T21:29:01.907044Z"
}

###
# group: Groups
# @name New Or Update Group
POST https://api.dev.navigator.mobileinsight.com/api/v2/groups
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1NDU0ODUsImlhdCI6MTY5NDE4NTQ4NSwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjM1LCJ1c2VybmFtZSI6ImpsYXJhQHRyb2NnbG9iYWwuY29tIiwidXNlcl9pZCI6MzUsImlkIjoiamxhcmFAdHJvY2dsb2JhbC5jb20ifQ.foapyL2b1VN6wTv0NDtbo-WLGOB1sikkxZIN7ycVtkU
Content-Type: application/json

{
  "group_id": 107,
  "group_name": "Other Sample Group",
  "client_id": 1,
  "is_active": false
}

###
# group: Groups
# @name Delete Group
DELETE https://api.dev.navigator.mobileinsight.com/api/v2/groups/107
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1NDU0ODUsImlhdCI6MTY5NDE4NTQ4NSwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjM1LCJ1c2VybmFtZSI6ImpsYXJhQHRyb2NnbG9iYWwuY29tIiwidXNlcl9pZCI6MzUsImlkIjoiamxhcmFAdHJvY2dsb2JhbC5jb20ifQ.foapyL2b1VN6wTv0NDtbo-WLGOB1sikkxZIN7ycVtkU

###
# group: Countries
# @name Meta Info
GET https://api.dev.navigator.mobileinsight.com/api/v1/countries:meta
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1NDU0ODUsImlhdCI6MTY5NDE4NTQ4NSwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjM1LCJ1c2VybmFtZSI6ImpsYXJhQHRyb2NnbG9iYWwuY29tIiwidXNlcl9pZCI6MzUsImlkIjoiamxhcmFAdHJvY2dsb2JhbC5jb20ifQ.foapyL2b1VN6wTv0NDtbo-WLGOB1sikkxZIN7ycVtkU

###
# group: Countries
# @name Metadata
HEAD https://api.dev.navigator.mobileinsight.com/api/v1/countries
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1NDU0ODUsImlhdCI6MTY5NDE4NTQ4NSwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjM1LCJ1c2VybmFtZSI6ImpsYXJhQHRyb2NnbG9iYWwuY29tIiwidXNlcl9pZCI6MzUsImlkIjoiamxhcmFAdHJvY2dsb2JhbC5jb20ifQ.foapyL2b1VN6wTv0NDtbo-WLGOB1sikkxZIN7ycVtkU

###
# group: Countries
# @name Sample Data
GET https://api.dev.navigator.mobileinsight.com/api/v1/countries:sample
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1NDU0ODUsImlhdCI6MTY5NDE4NTQ4NSwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjM1LCJ1c2VybmFtZSI6ImpsYXJhQHRyb2NnbG9iYWwuY29tIiwidXNlcl9pZCI6MzUsImlkIjoiamxhcmFAdHJvY2dsb2JhbC5jb20ifQ.foapyL2b1VN6wTv0NDtbo-WLGOB1sikkxZIN7ycVtkU

###
# group: Countries
# @name Get All Countries
GET https://api.dev.navigator.mobileinsight.com/api/v1/countries
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1NDU0ODUsImlhdCI6MTY5NDE4NTQ4NSwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjM1LCJ1c2VybmFtZSI6ImpsYXJhQHRyb2NnbG9iYWwuY29tIiwidXNlcl9pZCI6MzUsImlkIjoiamxhcmFAdHJvY2dsb2JhbC5jb20ifQ.foapyL2b1VN6wTv0NDtbo-WLGOB1sikkxZIN7ycVtkU

###
# group: Countries
# @name Get One Country
GET https://api.dev.navigator.mobileinsight.com/api/v1/countries/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1NDU0ODUsImlhdCI6MTY5NDE4NTQ4NSwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjM1LCJ1c2VybmFtZSI6ImpsYXJhQHRyb2NnbG9iYWwuY29tIiwidXNlcl9pZCI6MzUsImlkIjoiamxhcmFAdHJvY2dsb2JhbC5jb20ifQ.foapyL2b1VN6wTv0NDtbo-WLGOB1sikkxZIN7ycVtkU

###
# group: Countries
# @name GET Various Countries
GET https://api.dev.navigator.mobileinsight.com/api/v1/countries/1/2/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1NDU0ODUsImlhdCI6MTY5NDE4NTQ4NSwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjM1LCJ1c2VybmFtZSI6ImpsYXJhQHRyb2NnbG9iYWwuY29tIiwidXNlcl9pZCI6MzUsImlkIjoiamxhcmFAdHJvY2dsb2JhbC5jb20ifQ.foapyL2b1VN6wTv0NDtbo-WLGOB1sikkxZIN7ycVtkU

###
# group: Countries
# @name Filter
GET https://api.dev.navigator.mobileinsight.com/api/v1/countries/?
    country=Brazil
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1NDU0ODUsImlhdCI6MTY5NDE4NTQ4NSwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjM1LCJ1c2VybmFtZSI6ImpsYXJhQHRyb2NnbG9iYWwuY29tIiwidXNlcl9pZCI6MzUsImlkIjoiamxhcmFAdHJvY2dsb2JhbC5jb20ifQ.foapyL2b1VN6wTv0NDtbo-WLGOB1sikkxZIN7ycVtkU

###
# group: Widget Interactions
# @name Pin Widget
PUT http://navigator-dev.dev.local:5000/api/v1/interactions/pin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1NDU0ODUsImlhdCI6MTY5NDE4NTQ4NSwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjM1LCJ1c2VybmFtZSI6ImpsYXJhQHRyb2NnbG9iYWwuY29tIiwidXNlcl9pZCI6MzUsImlkIjoiamxhcmFAdHJvY2dsb2JhbC5jb20ifQ.foapyL2b1VN6wTv0NDtbo-WLGOB1sikkxZIN7ycVtkU
Content-Type: application/json

{
  "widget_id": 18616,
  "user_id": 35
}

###
# group: Widget Interactions
# @name UnPin Widget
DELETE http://navigator-dev.dev.local:5000/api/v1/interactions/pin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1NDU0ODUsImlhdCI6MTY5NDE4NTQ4NSwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjM1LCJ1c2VybmFtZSI6ImpsYXJhQHRyb2NnbG9iYWwuY29tIiwidXNlcl9pZCI6MzUsImlkIjoiamxhcmFAdHJvY2dsb2JhbC5jb20ifQ.foapyL2b1VN6wTv0NDtbo-WLGOB1sikkxZIN7ycVtkU
Content-Type: application/json

{
  "widget_id": 18616
}

###
# group: Widget Interactions
# @name Like Widget
PUT http://navigator-dev.dev.local:5000/api/v1/interactions/likes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1NDU0ODUsImlhdCI6MTY5NDE4NTQ4NSwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjM1LCJ1c2VybmFtZSI6ImpsYXJhQHRyb2NnbG9iYWwuY29tIiwidXNlcl9pZCI6MzUsImlkIjoiamxhcmFAdHJvY2dsb2JhbC5jb20ifQ.foapyL2b1VN6wTv0NDtbo-WLGOB1sikkxZIN7ycVtkU
Content-Type: application/json

{
  "object_uuid": "5a833d56-8e00-4f91-9a47-03c25067d338",
  "object_type": "widget"
}

###
# group: Widget Interactions
# @name Unlike Widget
DELETE http://navigator-dev.dev.local:5000/api/v1/interactions/likes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1NDU0ODUsImlhdCI6MTY5NDE4NTQ4NSwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjM1LCJ1c2VybmFtZSI6ImpsYXJhQHRyb2NnbG9iYWwuY29tIiwidXNlcl9pZCI6MzUsImlkIjoiamxhcmFAdHJvY2dsb2JhbC5jb20ifQ.foapyL2b1VN6wTv0NDtbo-WLGOB1sikkxZIN7ycVtkU
Content-Type: application/json

{
  "object_uuid": "5a833d56-8e00-4f91-9a47-03c25067d338",
  "object_type": "widget"
}

###
# group: Widget Location
# @name Get Widget Location
GET https://api.dev.navigator.mobileinsight.com/api/v2/widgets/location/434
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1NDU0ODUsImlhdCI6MTY5NDE4NTQ4NSwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjM1LCJ1c2VybmFtZSI6ImpsYXJhQHRyb2NnbG9iYWwuY29tIiwidXNlcl9pZCI6MzUsImlkIjoiamxhcmFAdHJvY2dsb2JhbC5jb20ifQ.foapyL2b1VN6wTv0NDtbo-WLGOB1sikkxZIN7ycVtkU

###
# group: Widget Location
# @name Update Widget Location
PATCH https://api.dev.navigator.mobileinsight.com/api/v2/widgets/location/434
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1NDU0ODUsImlhdCI6MTY5NDE4NTQ4NSwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjM1LCJ1c2VybmFtZSI6ImpsYXJhQHRyb2NnbG9iYWwuY29tIiwidXNlcl9pZCI6MzUsImlkIjoiamxhcmFAdHJvY2dsb2JhbC5jb20ifQ.foapyL2b1VN6wTv0NDtbo-WLGOB1sikkxZIN7ycVtkU
Content-Type: application/json

{
  "widget_location": {
    "lobipanel-parent-stateful_434_1": {
      "29ce4318-3df1-4172-9844-bd8a85964eb7": 1,
      "596c20b0-1a19-4c2b-92f9-e5926e43e0a6": 1
    }
  }
}

###
# group: Widget Location
# @name Update Widget Location POST
POST https://api.dev.navigator.mobileinsight.com/api/v2/widgets/location/434
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1NDU0ODUsImlhdCI6MTY5NDE4NTQ4NSwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjM1LCJ1c2VybmFtZSI6ImpsYXJhQHRyb2NnbG9iYWwuY29tIiwidXNlcl9pZCI6MzUsImlkIjoiamxhcmFAdHJvY2dsb2JhbC5jb20ifQ.foapyL2b1VN6wTv0NDtbo-WLGOB1sikkxZIN7ycVtkU
Content-Type: application/json

{
  "widget_location": {
    "lobipanel-parent-stateful_434_1": {
      "29ce4318-3df1-4172-9844-bd8a85964eb7": 1,
      "596c20b0-1a19-4c2b-92f9-e5926e43e0a6": 1
    }
  }
}
