name: Update .env on Main

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  update-env:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

          
      - name: Update env for production
        run: cp env/.env.production .env

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .env
          git commit -m "Update env for production"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
