
###
POST api.dev.navigator.mobileinsight.com/api/v1/login
Accept: application/json
x-auth-method: BasicAuth

{
username: Gcanelon@mobileinsight.com
password: 090512gj
}

###


###
PUT api.dev.navigator.mobileinsight.com/api/v2/widgets
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTY2MTE4NTcsImlhdCI6MTY5NjI1MTg1NywiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjE1Nzc5LCJ1c2VybmFtZSI6ImptZW5kb3phMUB0cm9jZ2xvYmFsLmNvbSIsInVzZXJfaWQiOjE1Nzc5LCJpZCI6ImptZW5kb3phMUB0cm9jZ2xvYmFsLmNvbSJ9.BYIxTAxBb6Yoip3oPEOhPCX9el1M1YAhByqPkeRdZD8

{
    "program_id": 1,
    "dashboard_id":557,
    "title":"Nuevo",
    "widget_id":278
}


###
PUT api.dev.navigator.mobileinsight.com/api/v2/dashboards
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTY2MTE4NTcsImlhdCI6MTY5NjI1MTg1NywiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjE1Nzc5LCJ1c2VybmFtZSI6ImptZW5kb3phMUB0cm9jZ2xvYmFsLmNvbSIsInVzZXJfaWQiOjE1Nzc5LCJpZCI6ImptZW5kb3phMUB0cm9jZ2xvYmFsLmNvbSJ9.BYIxTAxBb6Yoip3oPEOhPCX9el1M1YAhByqPkeRdZD8

{
    "dashboard_name": "Este es un nuevo dashboard"
}
