# Login
GET https://api.dev.navigator.mobileinsight.com/api/v1/user/session
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTYxMTk5MTYsImlhdCI6MTY5NTc1OTkxNiwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjE1Nzc5LCJ1c2VybmFtZSI6ImptZW5kb3phMUB0cm9jZ2xvYmFsLmNvbSIsInVzZXJfaWQiOjE1Nzc5LCJpZCI6ImptZW5kb3phMUB0cm9jZ2xvYmFsLmNvbSJ9.qi4R8IHjibsd3m5_gFytGgm2ZUb-341lStf1hFVonxY

###
# Logout
GET https://api.dev.navigator.mobileinsight.com/api/v1/logout
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTYxODk3OTUsImlhdCI6MTY5NTgyOTc5NSwiaXNzIjoiTW9iaWxlaW5zaWdodCIsInVzZXIiOjE1Nzc5LCJ1c2VybmFtZSI6ImptZW5kb3phMUB0cm9jZ2xvYmFsLmNvbSIsInVzZXJfaWQiOjE1Nzc5LCJpZCI6ImptZW5kb3phMUB0cm9jZ2xvYmFsLmNvbSJ9.J7ETkSNsgyXFXWjM3P_O7vhrpiiNLiFeibWKieGZGsQ
